--Insert Values into MIP Dim Table

TRUNCATE TABLE dim.MIP
SELECT * FROM dim.MIP

INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Visual Studio ALM: TFS Essentials','Three-day instructor-led training course on Azure and DevOps','TFS Essentials - Azure Super Powers','WorkshopPLUS',3,116,'Azure Super Powers Delivery',GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Windows PowerShell: Foundation Skills', 'Introduction to using PowerShell for system and application management', 'PowerShell Foundation Skils', 'WorkshopPLUS', 4, 139, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Office 365 - Developing Business Applications with PowerApps', 'Developing Business Application with PowerApps', 'Developing Business Applications with PowerApps', 'WorkshopPLUS', 1, 58, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Office 365 SharePoint Online: PowerApps and Flow for Administrators', 'two-day course that teaches you how to manage and support Power Apps and Microsoft Flow', 'PowerApps and Flow for Admins', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('The WorkshopPLUS - Dynamics 365 Customer Engagement: Development', 'Development course focuses on techniques used for building applications with Dynamics', 'Dynamics 365 Customer Engegement', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS – Microsoft Azure:  Application, Monitoring and Diagnostics for IT Professionals', 'Azure Application Monitoring and Diagnostics Workshop', 'Azure Application Monitoring and Diagnostics', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Data AI: Azure SQL Data Warehouse Essentials', 'Azure SQL Data Warehouse Essentials provides you the knowledge and tools necessary to understand the capabilities and usage of Azure SQL Data Warehouse databases', 'Azure SQL Data Warehouse Essentials', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('Data Platform Modernization Assessment for SQL', 'Data Platform Modernization Assessment for SQL to help you understand the blockers and methods moving from previous version of SQL Server', 'Data Platform Modernization for SQL', 'Assessment', 3, 53, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Data AI: Azure SQL Database Essentials', 'Azure SQL Database Essentials provides you the knowledge and tools necessary to understand the capabilites and usage of cloud database', 'Azure SQL Database Essentials', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Microsoft Azure: Security Best Practices', 'Best Practices with an understanding of key security concepts that apply for both the on-premises and Cloud environments', 'Azure Security Best Practices', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('Azure PaaS Solutions for Developers', 'Developer series provides your staff with a jumpstart on Azure Development, Application Migration and Debugging for PaaS.', 'Azure PaaS Solutions for Developers', 'WorkshopPLUS', 4, 139, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('Security: Azure Information Protection - Fundamentals', 'Azure Information Protection is a cloud-based solution that helps an organization to classify, label, and protect its documents and emails.', 'Azure Information Protection', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Office 365: Security and Compliance', 'Provides attendees with the deep knowledge and understanding of how to leverage the Security and Compliance features of Exchange and SharePoint', 'office 365 Security and Compliance', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Azure: AZ-900 Microsoft Azure Fundamentals 1 Day', 'Covers general cloud computing concepts as well as general cloud computing models and services', 'Azure Fundamentals', 'WorkshopPLUS', 1, 58, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS - Enterprise Mobile Device Management with Microsoft Intune', 'Enterprise Mobile Device Managemnt by using Microsoft Intune', 'Mobile Device Management with Intune', 'WorkshopPLUS', 3, 116, '', GETDATE())
INSERT INTO [dim].MIP (MipName,ShortDescription, ShortName, MipType, DeliveryDays, BilledHours, Notes, LastUpdated) VALUES ('WorkshopPLUS: DevOps Fundamentals', 'Introduces the business value of DevOps then walks the attendees through the essential practices required fro a healthy implementation of DevOps', 'DevOps Fundamentals', 'DevOps Fundamentals', 4, 139, '', GETDATE())


SELECT * FROM dim.MIP

